package com.certicode.jolibee_test_app.data.jollibeedata.tasks

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "tasks")
data class TasKModel(
    // The primary key for the task, which will be auto-generated by Room.
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    // The name of the task, corresponding to "Task Name" in the provided image.
    @ColumnInfo(name = "task_name")
    val taskName: String,

    // The unique identifier for the ship, as specified by the user's request.
    @ColumnInfo(name = "Purpose")
    val purpose: String,

    // The status of the task, corresponding to "Status" in the provided image.
    @ColumnInfo(name = "status")
    val status: String
)