package com.certicode.jolibee_test_app.data.jollibeedata.business

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "businesses")
data class BusinessModel(
    // The primary key for the business, which will be auto-generated by Room.
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    // The name of the business.
    @ColumnInfo(name = "business_name")
    val businessName: String,

    // The email address associated with the business.
    @ColumnInfo(name = "email")
    val email: String,

    // The categories associated with the business, stored as a comma-separated string.
    // A Room TypeConverter would be needed to handle this as a list of strings.
    @ColumnInfo(name = "categories")
    val categories: String,

    // The tags associated with the business, stored as a comma-separated string.
    // A Room TypeConverter would be needed to handle this as a list of strings.
    @ColumnInfo(name = "tags")
    val tags: String
)