package com.certicode.jolibee_test_app.data.jollibeedata.tags

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Defines a tag entity for the Room database.
 * The table is named "tags".
 */
@Entity(tableName = "tags")
data class TagsModel(
    // The primary key for the tag, which will be auto-generated by Room.
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    // The name of the tag.
    @ColumnInfo(name = "tag_name")
    val tagName: String
)