package com.certicode.jolibee_test_app.data.jollibeedata.people

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Defines a person entity for the Room database.
 * The table is named "people".
 */
@Entity(tableName = "people")
data class PeopleModel(
    // The primary key for the person, which will be auto-generated by Room.
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    // The name of the person.
    @ColumnInfo(name = "name")
    val name: String,

    // The email address of the person.
    @ColumnInfo(name = "email")
    val email: String,

    // The phone number of the person.
    @ColumnInfo(name = "phone")
    val phone: String,

    // The business associated with the person.
    @ColumnInfo(name = "business")
    val business: String,

    // The tags associated with the person, stored as a comma-separated string.
    // A Room TypeConverter would be needed to handle this as a list of strings.
    @ColumnInfo(name = "tags")
    val tags: String
)