package com.certicode.jolibee_test_app.data.jollibeedata.categories

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Defines a category entity for the Room database.
 * The table is named "categories".
 */
@Entity(tableName = "categories")
data class CategoryModel(
    // The primary key for the category, which will be auto-generated by Room.
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    // The name of the category.
    @ColumnInfo(name = "category_name")
    val categoryName: String
)